{"uuid": "b6e3334b-2981-469b-9142-0ffe50e6eb26", "children": ["2abeb3de-5083-45b0-9313-b614ab993230"], "befores": [{"name": "browser", "status": "passed", "start": 1691658214775, "stop": 1691658215611}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /wd/hub/session/522972036f057a4aad748852ff31d174/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa109a0fb20>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/conftest.py\", line 67, in browser\n    driver.close()\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 826, in urlopen\n    return self.urlopen(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 826, in urlopen\n    return self.urlopen(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 826, in urlopen\n    return self.urlopen(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 798, in urlopen\n    retries = retries.increment(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1691658219281, "stop": 1691658219285}], "start": 1691658214775, "stop": 1691658219285}